AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  shravanthTable:
    Type: String
    Default: 'shravanthTable'
    Description: created a demo table
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'


Resources:
  shravanthPutItems:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/putItems/putItems.shravanthPutItems
      Runtime: nodejs16.x
      CodeUri: ./dist/putItems
      Environment:
        Variables:
          MyTable: !Ref shravanthTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref shravanthTable
      Events:
        PostShravanthTable:
          Type: Api
          Properties:
            Path: /FName/{FName}/LName/{LName}/ssn/{ssn}/PostShravanthForm
            Method: POST

  shravanthGetItemsWithLimit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/getItemsWithLimit/getItemsWithLimit.shravanthGetItemsWithLimit
      Runtime: nodejs16.x
      CodeUri: ./dist/getItemsWithLimit
      Environment:
        Variables:
          MyTable: !Ref shravanthTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref shravanthTable
      Events:
        PostShravanthTable:
          Type: Api
          Properties:
            Path: /FName/{FName}/FetchShravanthFormWithLimit
            Method: GET

  shravanthGetAllItemsWithLimit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/lambdaReinvoke/getAllWithLimit.shravanthGetAllItemsWithLimit
      Runtime: nodejs16.x
      CodeUri: ./dist/lambdaReinvoke
      Environment:
        Variables:
          MyTable: !Ref shravanthTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref shravanthTable
      Events:
        PostShravanthTable:
          Type: Api
          Properties:
            Path: /FName/{FName}/FetchShravanthFormWithLimit
            Method: GET

  shravanthQueryItems:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/queryItems/queryItems.shravanthQueryItems
      Runtime: nodejs16.x
      CodeUri: ./dist/queryItems
      Environment:
        Variables:
          MyTable: !Ref shravanthTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref shravanthTable
      Events:
        PostShravanthTable:
          Type: Api
          Properties:
            Path: /FName/{FName}/shravanthQueryItems
            Method: GET
  shravanthUpdateItems:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/updateItems/updateItems.shravanthUpdateItems
      Runtime: nodejs16.x
      CodeUri: ./dist/updateItems
      Environment:
        Variables:
          MyTable: !Ref shravanthTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref shravanthTable
      Events:
        PostShravanthTable:
          Type: Api
          Properties:
            Path: /FName/{FName}/LName/{LName}/ssn/{ssn}/UpdateShravanthForm
            Method: POST

  shravanthDeleteItems:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/deleteItems/deleteItems.shravanthDeleteItems
      Runtime: nodejs16.x
      CodeUri: ./dist/deleteItems
      Environment:
        Variables:
          MyTable: !Ref shravanthTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref shravanthTable
      Events:
        PostShravanthTable:
          Type: Api
          Properties:
            Path: /FName/{FName}/ssn/{ssn}/DeleteShravanthForm
            Method: DELETE

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref shravanthTable
      AttributeDefinitions:
        - AttributeName: FName
          AttributeType: S
        - AttributeName: ssn
          AttributeType: S
      KeySchema:
        - AttributeName: FName
          KeyType: HASH
        - AttributeName: ssn
          KeyType: RANGE

      BillingMode: PAY_PER_REQUEST


